// CA Daily Portal — Config

// Auth helpers — localStorage only
window.getUser   = () => JSON.parse(localStorage.getItem("ca_user") || "null");
window.setUser   = (u) => localStorage.setItem("ca_user", JSON.stringify(u));
window.clearUser = () => localStorage.removeItem("ca_user");
window.isAdmin   = () => { const u = getUser(); return !!(u && u.role === "admin"); };
window.isLogged  = () => !!getUser();

window.requireLogin = () => { if (!isLogged()) { window.location.href = "login.html"; return false; } return true; };
window.requireAdmin = () => { if (!isAdmin()) { window.location.href = "index.html"; return false; } return true; };

// Fetch articles from static JSON (generated by GitHub Actions pipeline)
window.fetchArticles = async () => {
  const res = await fetch('data/articles.json?t=' + Date.now());
  if (!res.ok) throw new Error("Failed to load articles.json");
  const json = await res.json();
  return json.articles || [];
};

// Quiz localStorage helpers
window.getQuizHistory = () => { try { return JSON.parse(localStorage.getItem("ca_quiz") || "[]"); } catch { return []; } };
window.saveQuizResult = (r) => { const h = getQuizHistory(); h.unshift(r); localStorage.setItem("ca_quiz", JSON.stringify(h.slice(0, 50))); };
window.getBookmarks   = () => { try { return JSON.parse(localStorage.getItem("ca_bookmarks") || "{}"); } catch { return {}; } };
window.saveBookmarks  = (b) => localStorage.setItem("ca_bookmarks", JSON.stringify(b));
window.getReadHistory = () => { try { return JSON.parse(localStorage.getItem("ca_read") || "[]"); } catch { return []; } };
window.markRead       = (id) => { const h = getReadHistory(); if (!h.includes(id)) { h.unshift(id); localStorage.setItem("ca_read", JSON.stringify(h.slice(0, 200))); } };

window.trackVisit = () => {
  const u = getUser();
  const visits = JSON.parse(localStorage.getItem("ca_visits") || "[]");
  visits.push({ time: new Date().toISOString(), page: location.pathname, user: u?.email || "guest" });
  localStorage.setItem("ca_visits", JSON.stringify(visits.slice(-500)));
};
