// CA Daily Portal — Config
// Supabase used for Google Auth ONLY — data comes from static JSON

const SUPABASE_URL = "https://fwuzyilojfkglrjhmedh.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3dXp5aWxvamZrZ2xyamhtZWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5NDQwMTcsImV4cCI6MjA5MjUyMDAxN30.ydTQlQBem1l7rUDLyli9EZyurCnFaxsTr0YOojrJOTM";

// Auth helpers — localStorage + Supabase Google session
window.getUser   = () => JSON.parse(localStorage.getItem("ca_user") || "null");
window.setUser   = (u) => localStorage.setItem("ca_user", JSON.stringify(u));
window.clearUser = async () => {
  localStorage.removeItem("ca_user");
  if(window._supabase) await window._supabase.auth.signOut();
};
window.isAdmin   = () => { const u = getUser(); return !!(u && u.role === "admin"); };
window.isLogged  = () => !!getUser();

// Handle Google OAuth redirect on any page (only if Supabase loaded)
(async () => {
  try {
    if (typeof supabase === 'undefined') return;
    window._supabase = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
    const { data: { session } } = await window._supabase.auth.getSession();
    if (session && session.user && !getUser()) {
      const u = session.user;
      setUser({
        name:   u.user_metadata?.full_name || u.email.split("@")[0],
        email:  u.email,
        role:   "user",
        avatar: (u.user_metadata?.full_name || u.email).slice(0,2).toUpperCase(),
      });
      if (location.pathname.includes("login")) window.location.href = "index.html";
    }
  } catch(e) {}
})();

window.requireLogin = () => { if (!isLogged()) { window.location.href = "login.html"; return false; } return true; };
window.requireAdmin = () => { if (!isAdmin()) { window.location.href = "index.html"; return false; } return true; };

// Fetch articles from static JSON (generated by GitHub Actions pipeline)
window.fetchArticles = async () => {
  const res = await fetch('data/articles.json?t=' + Date.now());
  if (!res.ok) throw new Error("Failed to load articles.json");
  const json = await res.json();
  return json.articles || [];
};

// Quiz localStorage helpers
window.getQuizHistory = () => { try { return JSON.parse(localStorage.getItem("ca_quiz") || "[]"); } catch { return []; } };
window.saveQuizResult = (r) => { const h = getQuizHistory(); h.unshift(r); localStorage.setItem("ca_quiz", JSON.stringify(h.slice(0, 50))); };
window.getBookmarks   = () => { try { return JSON.parse(localStorage.getItem("ca_bookmarks") || "{}"); } catch { return {}; } };
window.saveBookmarks  = (b) => localStorage.setItem("ca_bookmarks", JSON.stringify(b));
window.getReadHistory = () => { try { return JSON.parse(localStorage.getItem("ca_read") || "[]"); } catch { return []; } };
window.markRead       = (id) => { const h = getReadHistory(); if (!h.includes(id)) { h.unshift(id); localStorage.setItem("ca_read", JSON.stringify(h.slice(0, 200))); } };

window.trackVisit = () => {
  const u = getUser();
  const visits = JSON.parse(localStorage.getItem("ca_visits") || "[]");
  visits.push({ time: new Date().toISOString(), page: location.pathname, user: u?.email || "guest" });
  localStorage.setItem("ca_visits", JSON.stringify(visits.slice(-500)));
};
