// NewsPrep — Config

// Auth helpers — sessionStorage (clears when tab/browser closes)
window.getUser   = () => JSON.parse(sessionStorage.getItem("ca_user") || "null");
window.setUser   = (u) => sessionStorage.setItem("ca_user", JSON.stringify(u));
window.clearUser = () => sessionStorage.removeItem("ca_user");
window.isAdmin   = () => { const u = getUser(); return !!(u && u.role === "admin"); };
window.isLogged  = () => !!getUser();

window.requireLogin = () => { if (!isLogged()) { window.location.href = "login.html"; return false; } return true; };
window.requireAdmin = () => { if (!isAdmin()) { window.location.href = "index.html"; return false; } return true; };

// Fetch articles from static JSON (generated by GitHub Actions pipeline)
window.fetchArticles = async () => {
  const res = await fetch('data/articles.json?t=' + Date.now());
  if (!res.ok) throw new Error("Failed to load articles.json");
  const json = await res.json();
  return json.articles || [];
};

// Quiz localStorage helpers — user-specific keys
window.getQuizHistory = () => { try { const u=getUser(); const k=u?`ca_quiz_${u.email}`:'ca_quiz'; return JSON.parse(localStorage.getItem(k) || "[]"); } catch { return []; } };
window.saveQuizResult = (r) => { const u=getUser(); const k=u?`ca_quiz_${u.email}`:'ca_quiz'; const h = getQuizHistory(); h.unshift(r); localStorage.setItem(k, JSON.stringify(h.slice(0, 50))); };
window.getBookmarks   = () => { try { const u=getUser(); const k=u?`ca_bookmarks_${u.email}`:'ca_bookmarks'; return JSON.parse(localStorage.getItem(k) || "{}"); } catch { return {}; } };
window.saveBookmarks  = (b) => { const u=getUser(); const k=u?`ca_bookmarks_${u.email}`:'ca_bookmarks'; localStorage.setItem(k, JSON.stringify(b)); };
window.getReadHistory = () => { try { const u=getUser(); const k=u?`ca_read_${u.email}`:'ca_read'; return JSON.parse(localStorage.getItem(k) || "[]"); } catch { return []; } };
window.markRead       = (id) => { const u=getUser(); const k=u?`ca_read_${u.email}`:'ca_read'; const h = getReadHistory(); if (!h.includes(id)) { h.unshift(id); localStorage.setItem(k, JSON.stringify(h.slice(0, 200))); } };

// Category-wise read tracking — user-specific
window.getCatReads = () => { try { const u=getUser(); const k=u?`ca_cat_reads_${u.email}`:'ca_cat_reads'; return JSON.parse(localStorage.getItem(k) || "{}"); } catch { return {}; } };
window.markCatRead = (category) => {
  if(!category) return;
  const u=getUser(); const k=u?`ca_cat_reads_${u.email}`:'ca_cat_reads';
  const today = new Date().toISOString().slice(0,10);
  const data = getCatReads();
  if(!data[today]) data[today] = {};
  data[today][category] = (data[today][category] || 0) + 1;
  const keys = Object.keys(data).sort();
  if(keys.length > 30) keys.slice(0, keys.length - 30).forEach(k2 => delete data[k2]);
  localStorage.setItem(k, JSON.stringify(data));
};

window.trackVisit = () => {
  const u = getUser();
  const visits = JSON.parse(localStorage.getItem("ca_visits") || "[]");
  visits.push({ time: new Date().toISOString(), page: location.pathname, user: u?.email || "guest" });
  localStorage.setItem("ca_visits", JSON.stringify(visits.slice(-500)));
};

// ── Theme (dark / light mode) ──────────────────────────────────────────────
window.getTheme    = () => localStorage.getItem("ca_theme") || "dark";
window.setTheme    = (t) => { localStorage.setItem("ca_theme", t); applyTheme(t); };
window.toggleTheme = () => setTheme(getTheme() === "dark" ? "light" : "dark");

window.applyTheme = (theme) => {
  const root = document.documentElement;
  if (theme === "light") {
    root.style.setProperty("--bg",      "#f5f6fa");
    root.style.setProperty("--surface", "#ffffff");
    root.style.setProperty("--border",  "#dde1e7");
    root.style.setProperty("--text",    "#1a1d23");
    root.style.setProperty("--muted",   "#6b7280");
    root.style.setProperty("--card",    "#ffffff");
    root.style.setProperty("--accent",  "#d4900a");
    root.style.setProperty("--green",   "#16a34a");
    root.style.setProperty("--blue",    "#2563eb");
    root.style.setProperty("--red",     "#dc2626");
  } else {
    root.style.setProperty("--bg",      "#0d1117");
    root.style.setProperty("--surface", "#161b22");
    root.style.setProperty("--border",  "#30363d");
    root.style.setProperty("--text",    "#e6edf3");
    root.style.setProperty("--muted",   "#7d8590");
    root.style.setProperty("--card",    "#1c2128");
    root.style.setProperty("--accent",  "#f4b942");
    root.style.setProperty("--green",   "#3fb950");
    root.style.setProperty("--blue",    "#58a6ff");
    root.style.setProperty("--red",     "#e05c5c");
  }
  // Update toggle button label if present
  const btn = document.getElementById("themeToggleBtn");
  if (btn) btn.textContent = theme === "light" ? "🌙 Dark Mode" : "☀️ Light Mode";
};

// Auto-apply saved theme on every page load
(function() { applyTheme(getTheme()); })();
